# Generated by Django 5.2.7 on 2025-10-25 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('language', models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('HI', 'Hindi'), ('ES', 'Spanish'), ('DE', 'German')], default='EN', max_length=5)),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('BLOCK', 'block'), ('IN-ACTIVE', 'in-active')], default='ACTIVE', max_length=10)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('max_coordinators', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('COORDINATOR', 'Coordinator')], default='COORDINATOR', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.organization')),
            ],
        ),
    ]
